### ISSUE TITLE
asm and llvm_asm

### ISSUE THREAD

**Issue by hellow554** [Narasimha1997/r3#2]
`asm` is not behind a feature gate on nightly and will be stable on 1.59.0: https://doc.rust-lang.org/nightly/core/arch/macro.asm.html

`llvm_asm` will be removed so you should remove it as well

**Comment by Narasimha1997** [comment]
Hi, I have made the changes as you suggested. I don't remember why I enabled `llvm_asm` feature though it is not used anywhere in the codebase. (Maybe I was experimenting something and left it as it is). 
Yeah about `asm` I am using `rustc 1.59.0-nightly (532d2b14c 2021-12-03)` and it throws an error if `#![feature(naked_functions)]` is removed. So leaving it untouched.
